### ISSUE TITLE
Exceptions not caught by base class reference

### ISSUE THREAD

**Issue by landswellsong** [pcingola/bds#5]
The `try`-`catch` block only matches the exception by the final derived class. Trying to capture an exception by its base class (including the root `Exception` class) causes the exception to go unhandled.

BDS version: `bds 3.2 (build 2021-08-29 12:41), by Pablo Cingolani`

### Example code that causes the error
```
class MyException extends Exception { }

try {
    throw new OurException()
} catch(Exception e) {
    println "CATCH: $e"
}
```

### Two-level class hierarchy with the same error
To make sure the issue is unrelated to `Exception` class being a native one
```
class MyException extends Exception { }
class OurException extends MyException { }

try {
    throw new OurException()
} catch(MyException e) {
    println "CATCH: $e"
}
```

**Comment by pcingola** [comment]
Fixed.
